### ISSUE TITLE
Performance issue caused by NamespacedSurfaceRuleSource

### ISSUE THREAD

**Issue by racoonman2** [Glitchfiend/TerraBlender#159]
### What's the issue you encountered?

Performance is noticeably slower with TerraBlender, even when no other mods are installed. It seems this is due to NamespacedSurfaceRuleSource calling context.biome.get() for every non empty block in the chunk, while this only happens along the surface in vanilla. This could be fixed by grouping surface rules into a single sequence instead of having them be registered per biome namespace.

### How can the issue be reproduced?

Create a world with TerraBlender installed

### Mod Version

1.20.2

### Additional information

Heres some quick tests done by someone in the TerraForged discord. They arent perfect, but they still demonstrate the performance differences pretty well (note that the fix column refers to TerraBlender with it's surface rule api disabled)
![image](https://github.com/Glitchfiend/TerraBlender/assets/81602236/b27c6604-38b6-4188-a667-8008d736e578)

**Comment by Uniter343** [comment]
Hi, the guy who did that test here. I've also done the same thing for Terrablender with Regions Unexplored (which had a surface rule problem on their own which they solved in RU 0.5.5)
Here are those results.

![image-39](https://github.com/Glitchfiend/TerraBlender/assets/54006732/cf971e12-013b-4fa6-ba8f-7d8932d15328)

**Comment by racoonman2** [comment]
To clarify, the version of TerraBlender used in the fix was modified to still work with Regions Unexplored's surface rules, so the world gen is still the same as normal TerraBlender regardless of the surface api being disabled

**Comment by TrickShow** [comment]
This is also an issue in 1.20.1

**Comment by Uniter343** [comment]
It's an Issue on all Terrablender versions as far as I can tell.

**Comment by JT122406** [comment]
Based on this someone made a fix?  If so why not open a pr for it

**Comment by MagmaBro123** [comment]
Please resolve this. Any biome mod that depends on this is unusable and slows chunk loading to a snail's pace.

**Comment by Veynam** [comment]
Gosh took me a while to find what mod was suddenly causing us slowdown. Glad this was already found reported. Hope it gets fixed soon

**Comment by PakoJones88** [comment]
The diminution in performance is pretty noticeable, especially in big modpacks. Are the devs working on a fix?

**Comment by Fyoncle** [comment]
You guys can use [TerraBlenderFix](https://modrinth.com/mod/terrablenderfix) to get rid of this chaotic lag

**Comment by Uniter343** [comment]
That mod was actually made by racoonman2 who originally brought this issue up.

**Comment by Fyoncle** [comment]
> That mod was actually made by racoonman2 who originally brought this issue up.

Yep

**Comment by DarthCaesium** [comment]
TerraBlender devs, I'm still waiting on a fix (in fact I have observed this behaviour for as long as TerraBlender has existed). I literally cannot use Elytras because of this performance issue. With this mod installed, chunk generation can just barely keep up with my speed and will rather quickly struggle and become slower than me, causing me to go into unloaded chunks. This does not happen without this mod, where I can load the chunks in front me without any issues.

**Comment by Fyoncle** [comment]
> Terrablender devs, I'm still waiting on a fix. I literally cannot use Elytras because of this performance issue. With this mod installed, chunk generation can just barely keep up with my speed and will rather quickly struggle and become slower than me, causing me to go into unloaded chunks. This does not happen without this mod, where I can load the chunks in front me without any issues.

Same here, pain.

**Comment by MagmaSlime123** [comment]
A lot of well-known mods rely on this. I have the same issue as well.

**Comment by Luviam** [comment]
Can't wait for the Terrablender devs to see this github issue in the year 2183.

**Comment by Fyoncle** [comment]
> Can't wait for the Terrablender devs to see this github issue in the year 2183.

Exactly

**Comment by MagmaSlime123** [comment]
> Can't wait for the Terrablender devs to see this github issue in the year 2183.

Lol, same.

**Comment by MarioSMB** [comment]
Chunk loading and world generation is *the* most resource intensive operation in Minecraft, ensuring it's as optimised as possible is vital to the game's performance and stability.  

**The fact that such a huge bottleneck has remained unresolved in a dependency for every major biome mod, is incredibly disappointing.**  
This issue deserves more severity than being ignored for multiple years, though at this point mod developers are just being encouraged to steer clear of TerraBlender wherever possible.

**Comment by Fyoncle** [comment]
> Chunk loading and world generation is _the_ most resource intensive operation in Minecraft, ensuring it's as optimised as possible is vital to the game's performance and stability.
> 
> **The fact that such a huge bottleneck has remained unresolved in a dependency for every major biome mod, is incredibly disappointing.** This issue deserves more severity than being ignored for multiple years, though at this point mod developers are just being encouraged to steer clear of TerraBlender wherever possible.

I agree!

**Comment by MagmaSlime123** [comment]
If this mod is dead, please archive and/or remove it. This has been rotting here for 2 years.

**Comment by MarioSMB** [comment]
> If this mod is dead, please archive and/or remove it. This has been rotting here for 2 years.

Last update to the mod was 9 days ago, there are a few possibilities here:  
- They haven't seen this issue. Unlikely IMO, as any respectable developer will check their issue page at least once in TWO YEARS
- They don't know how to resolve this. Some acknowledgement of the issue would be appreciated in this case, and the community may even help them resolve it (as raccoonman2 attempted with TerraBlenderFix)
- They don't care. This is unfortunately a worst-case scenario, and it's why projects like Biolith are being developed to replace it

I am appreciative of the time and effort put into developing a shared library that eases compatibility with most biome mods, and I would not encourage anyone to attack the developers over this.  
But I am hoping the developers (@Adubbz) will bring some much-needed attention to the issue or at the least let everyone know they are aware of it.   

P.S. Please avoid filling the issue comments with replies that could be reactions (e.g. Same or I agree), I know this problem is frustrating but it would be best to keep replies constructive and respectfully candid.

**Comment by Fyoncle** [comment]
> > If this mod is dead, please archive and/or remove it. This has been rotting here for 2 years.
> 
> Last update to the mod was 9 days ago, there are a few possibilities here:
> 
>     * They haven't seen this issue. Unlikely IMO, as any respectable developer will check their issue page at least once in TWO YEARS
> 
>     * They don't know how to resolve this. Some acknowledgement of the issue would be appreciated in this case, and the community may even help them resolve it (as raccoonman2 attempted with TerraBlenderFix)
> 
>     * They don't care. This is unfortunately a worst-case scenario, and it's why projects like Biolith are being developed to replace it
> 
> 
> I am appreciative of the time and effort put into developing a shared library that eases compatibility with most biome mods, and I would not encourage anyone to attack the developers over this. But I am hoping the developers ([@Adubbz](https://github.com/Adubbz)) will bring some much-needed attention to the issue or at the least let everyone know they are aware of it.
> 
> P.S. Please avoid filling the issue comments with replies that could be reactions (e.g. Same or I agree), I know this problem is frustrating but it would be best to keep replies constructive and respectfully candid.

It's like a dead thread, I don't see a point in keeping it "constructive" when the original message's owner even has a mod that is open source which fixes that issue easily. They don't care is the most likely scenario here as it is not a big problem but looks easy fixable from what TerraBlenderFix does. The updates you're talking about which are 9 days ago is 26.1.1 and NO ONE can guarantee they will ever support 1.20.1 or 1.21.1 again because they updated to a very unrelated version. Probably that and every future update will have the same bug over and over again.

Let's say the issue is very big that they couldn't find a solution for 2 years, then why not tell us? Because they probably don't even know this issue exists.

**Comment by MarioSMB** [comment]
TerraBlenderFix is only a workaround and unfortunately it has a [biome corruption bug](https://github.com/racoonman2/TerraBlenderFix/issues/1).  

Yes, it is likely they will never look at this and in a few years alternatives will replace TerraBlender.  
In the meantime however, we can remain civil.  

There are still mod developers porting to TerraBlender, it looks bad if they have to be linked a non-constructive thread as proof of its shortcomings.

**Comment by Fyoncle** [comment]
> TerraBlenderFix is only a workaround and unfortunately it has a [biome corruption bug](https://github.com/racoonman2/TerraBlenderFix/issues/1).
> 
> Yes, it is likely they will never look at this and in a few years alternatives will replace TerraBlender. In the meantime however, we can remain civil.
> 
> There are still mod developers porting to TerraBlender, it looks bad if they have to be linked a non-constructive thread as proof of its shortcomings.

That "bug" is only Nature's Spirit fault as far as I know.
The mods that replaces TerraBlender won't be for 1.20.1 nor 1.21.1 and even if they do no developer will get out of their way to update the 1.20.1 versions of their mod to integrate a whole new API.

**Comment by MarioSMB** [comment]
Unfortunately the issue affects several mod combinations as noted in the comments - any mod that is not careful with its surface rules will be corrupted by the fix essentially, that includes popular mods like Oh The Biomes We've Gone.  

For the record, Biolith *is* being developed for 1.20.1 and advertises TerraBlender compatibility, so there is hope for the future.  
We need only be patient and respectful in the meantime!

**Comment by Redls07** [comment]
Judging by the author's messages in the Discord, he is notified of the problem, but simply does not want to fix it for certain reasons.
You can read the discussion in more detail [here](https://discord.com/channels/138056667865546752/927537933718802482/1316469075815174176).

**Comment by MarioSMB** [comment]
Thank you for the reference, I'll share the transcript here for posterity (and for those who don't use Discord):  

![Image](https://github.com/user-attachments/assets/c3a7cc4b-df7a-4b72-ad76-000e04f376a7)  
![Image](https://github.com/user-attachments/assets/4be988d8-8e8e-4d32-9bba-d163a1421462)  
![Image](https://github.com/user-attachments/assets/8cc53f2c-d2b0-48e6-bc0d-bd58563f14bc)

**Comment by MagmaSlime123** [comment]
> > If this mod is dead, please archive and/or remove it. This has been rotting here for 2 years.
> 
> Last update to the mod was 9 days ago, there are a few possibilities here:
> 
> * They haven't seen this issue. Unlikely IMO, as any respectable developer will check their issue page at least once in TWO YEARS
> * They don't know how to resolve this. Some acknowledgement of the issue would be appreciated in this case, and the community may even help them resolve it (as raccoonman2 attempted with TerraBlenderFix)
> * They don't care. This is unfortunately a worst-case scenario, and it's why projects like Biolith are being developed to replace it
> 
> I am appreciative of the time and effort put into developing a shared library that eases compatibility with most biome mods, and I would not encourage anyone to attack the developers over this. But I am hoping the developers ([@Adubbz](https://github.com/Adubbz)) will bring some much-needed attention to the issue or at the least let everyone know they are aware of it.
> 
> P.S. Please avoid filling the issue comments with replies that could be reactions (e.g. Same or I agree), I know this problem is frustrating but it would be best to keep replies constructive and respectfully candid.

I'm not attacking anyone, just a bit annoyed.

**Comment by Poopchungus** [comment]
hey just putting my 2 cents in so this issue does not die but stuff like this should be fixed especially when someone makes their own mod that fixes it so I know the devs can as well

**Comment by Adubbz** [comment]
This is fixed.

**Comment by MarioSMB** [comment]
This is fixed in 26.3*.  

Do you intend to backport the fix to active modding versions?
