### ISSUE TITLE
Dedicated Server Crash

### ISSUE THREAD

**Issue by Mattabase** [Glitchfiend/TerraBlender#17]
### What's the issue you encountered?

Dedicated server crashes when starting server

### How can the issue be reproduced?

1. Setup a Forge 1.18.1-39.0.36 server using the official installer
2. Install TerraBlender-forge-1.18.1-1.1.0.61
3. Launch Server

### Logs

https://gist.github.com/Mattabase/db4c20bc2bb3652d158e5822d998feae

### Mod Version

1.1.0.61

**Comment by Adubbz** [comment]
This should be fixed now

**Comment by Mattabase** [comment]
Crash still occurring in 1.1.0.62

 https://gist.github.com/Mattabase/57bccb281cf09ed38d8a76abf3d02251

**Comment by Adubbz** [comment]
Fixed again... Annoying, since it doesn't happen in a dev environment
